[package]
name = "blackjack-rs"
version = "0.1.0"
edition = "2024"
description = "A simple blackjack libary + CLI implementation"
repository = "https://github.com/the-penwing/blackjack-rs"
license = "AGPL-3.0-only"
keywords = ["blackjack", "cli", "game", "libary"]

[dependencies]
rand = "0.10.2"

[profile.release]
opt-level = "s"
strip = true
lto = "thin"
codegen-units = 1
