[package]
name = "blackjack-rs"
description = "A simple blackjack libary + CLI implementation"
keywords = ["game", "blackjack", "libary", "cli"]
repository = "https://github.com/the-penwing/blackjack-rs"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "AGPL-3.0-only"
license-file = "LICENSE"

[dependencies]
rand = "0.10.2"
